export const LOCATIONS = [
  { name: "Автогонки", imagesrc: "./images/locations/racing.webp" },
  { name: "Автомойка", imagesrc: "./images/locations/carwash.webp" },
  { name: "Аквапарк", imagesrc: "./images/locations/aquapark.webp" },
  { name: "Аптека", imagesrc: "./images/locations/pharmacy.webp" },
  {
    name: "Археологический музей",
    imagesrc: "./images/locations/archeologyMuseum.webp",
  },
  { name: "Аэропорт", imagesrc: "./images/locations/airport.webp" },
  { name: "АЭС", imagesrc: "./images/locations/aes.webp" },
  { name: "База террористов", imagesrc: "./images/locations/terror-base.webp" },
  { name: "Бал", imagesrc: "./images/locations/bal.webp" },
  { name: "Банк", imagesrc: "./images/locations/bank.webp" },
  {
    name: "Бермудский треугольник",
    imagesrc: "./images/locations/bermud3.webp",
  },
  { name: "Библиотека", imagesrc: "./images/locations/library.webp" },
  { name: "Боксерский матч", imagesrc: "./images/locations/boxing.webp" },
  { name: "Болото Шрека", imagesrc: "./images/locations/shrek.webp" },
  {
    name: "Ботанический сад",
    imagesrc: "./images/locations/botanicGarden.webp",
  },
  { name: "Боулинг", imagesrc: "./images/locations/bowling.webp" },
  { name: "Буддийский храм", imagesrc: "./images/locations/buddaTemple.webp" },
  {
    name: "Вегетарианский ресторан",
    imagesrc: "./images/locations/vegetarianRest.webp",
  },
  {
    name: "Вертолетная площадка",
    imagesrc: "./images/locations/helicopterPoint.webp",
  },
  { name: "Ветклиника", imagesrc: "./images/locations/vetClinic.webp" },
  { name: "Вечеринка", imagesrc: "./images/locations/party.webp" },
  { name: "Виноградник", imagesrc: "./images/locations/grapeGarden.webp" },
  { name: "Военная база", imagesrc: "./images/locations/millitaryBase.webp" },
  { name: "Выставка кошек", imagesrc: "./images/locations/catEXPO.webp" },
  {
    name: "Геймерская конференция",
    imagesrc: "./images/locations/cybersport.webp",
  },
  { name: "Гольф-клуб", imagesrc: "./images/locations/golf.webp" },
  { name: "Дача", imagesrc: "./images/locations/dacha.webp" },
  {
    name: "Дворец бракосочетания",
    imagesrc: "./images/locations/weddingHouse.webp",
  },
  { name: "Дельфинарий", imagesrc: "./images/locations/dolphins.webp" },
  { name: "Деревня", imagesrc: "./images/locations/village.webp" },
  { name: "Летний лагерь", imagesrc: "./images/locations/summercamp.webp" },
  { name: "Детский сад", imagesrc: "./images/locations/kinderGarden.webp" },
  { name: "Дом лесника", imagesrc: "./images/locations/lesnik.webp" },
  { name: "Дом на колесах", imagesrc: "./images/locations/travelCar.webp" },
  { name: "Дом престарелых", imagesrc: "./images/locations/nursingHome.webp" },
  { name: "Дьюти-фри", imagesrc: "./images/locations/dutyfree.webp" },
  { name: "Завод", imagesrc: "./images/locations/factory.webp" },
  { name: "Замок", imagesrc: "./images/locations/castle.webp" },
  { name: "Замок Дракулы", imagesrc: "./images/locations/dracula.webp" },
  { name: "Заправка", imagesrc: "./images/locations/gasStation.webp" },
  { name: "Заседание ООН", imagesrc: "./images/locations/oun.webp" },
  { name: "Зоопарк", imagesrc: "./images/locations/zoo.webp" },
  { name: "Иглу", imagesrc: "./images/locations/iglu.webp" },
  { name: "Икеа", imagesrc: "./images/locations/IKEA.webp" },
  { name: "Инопланетный корабль", imagesrc: "./images/locations/ufo.webp" },
  { name: "Ипподром", imagesrc: "./images/locations/ippodrom.webp" },
  { name: "Казино", imagesrc: "./images/locations/casino.webp" },
  { name: "Канатная дорога", imagesrc: "./images/locations/cableroad.webp" },
  { name: "Киностудия", imagesrc: "./images/locations/kinostudio.webp" },
  { name: "Кинотеатр", imagesrc: "./images/locations/cinema.webp" },
  { name: "Кладбище", imagesrc: "./images/locations/cemetery.webp" },
  { name: "Компьютерный клуб ", imagesrc: "./images/locations/cyberclub.webp" },
  { name: "Конференция", imagesrc: "./images/locations/conference.webp" },
  { name: "Космодром", imagesrc: "./images/locations/cosmodrom.webp" },
  { name: "Космос", imagesrc: "./images/locations/Space.webp" },
  { name: "Лабиринт", imagesrc: "./images/locations/maze.webp" },
  {
    name: "Ледяной дворец Снежной Королевы",
    imagesrc: "./images/locations/snowqueen.webp",
  },
  { name: "Лесопилка", imagesrc: "./images/locations/sawmill.webp" },
  {
    name: "Магазин косметики",
    imagesrc: "./images/locations/beautystore.webp",
  },
  { name: "Магазин одежды", imagesrc: "./images/locations/clothesStore.webp" },
  {
    name: "Магазин электроники",
    imagesrc: "./images/locations/techstore.webp",
  },
  { name: "Метро", imagesrc: "./images/locations/metro.webp" },
  { name: "Модный показ", imagesrc: "./images/locations/modeling.webp" },
  { name: "Музей", imagesrc: "./images/locations/museum.webp" },
  { name: "Ночной клуб", imagesrc: "./images/locations/nightClub.webp" },
  { name: "Обсерватория", imagesrc: "./images/locations/observatory.webp" },
  { name: "Общественный туалет", imagesrc: "./images/locations/wc.webp" },
  { name: "Океанариум", imagesrc: "./images/locations/oceanarium.webp" },
  { name: "Океанский лайнер", imagesrc: "./images/locations/titanic.webp" },
  { name: "Отель", imagesrc: "./images/locations/hotel.webp" },
  { name: "Парк", imagesrc: "./images/locations/park.webp" },
  { name: "Парк развлечений", imagesrc: "./images/locations/disneyland.webp" },
  { name: "Песочница", imagesrc: "./images/locations/sandbox.webp" },
  { name: "Пикник", imagesrc: "./images/locations/picnic.webp" },
  { name: "Пиратский корабль", imagesrc: "./images/locations/pirat-ship.webp" },
  {
    name: "Площадка для воркаута",
    imagesrc: "./images/locations/workout.webp",
  },
  { name: "Площадь", imagesrc: "./images/locations/square.webp" },
  { name: "Пляж", imagesrc: "./images/locations/beach.webp" },
  { name: "Подвал", imagesrc: "./images/locations/basement.webp" },
  { name: "Подводная лодка", imagesrc: "./images/locations/submarine.webp" },
  { name: "Пожарная часть", imagesrc: "./images/locations/firestation.webp" },
  { name: "Поликлиника", imagesrc: "./images/locations/clinic.webp" },
  { name: "Полицейский участок", imagesrc: "./images/locations/police.webp" },
  {
    name: "Замок с привидениями",
    imagesrc: "./images/locations/ghosthouse.webp",
  },
  { name: "Порт", imagesrc: "./images/locations/port.webp" },
  {
    name: "Приют для собак",
    imagesrc: "./images/locations/dogAdoptation.webp",
  },
  { name: "Пустыня", imagesrc: "./images/locations/desert.webp" },
  {
    name: "Резиденция Дед Мороза",
    imagesrc: "./images/locations/santaHouse.webp",
  },
  { name: "Ресторан", imagesrc: "./images/locations/restaurant.webp" },
  { name: "Рок-концерт", imagesrc: "./images/locations/rockConcert.webp" },
  { name: "Рынок", imagesrc: "./images/locations/market.webp" },
  { name: "Салон красоты", imagesrc: "./images/locations/spa.webp" },
  { name: "Салон татуировок", imagesrc: "./images/locations/tatto.webp" },
  { name: "Самолёт", imagesrc: "./images/locations/plane.webp" },
  { name: "Сауна", imagesrc: "./images/locations/sauna.webp" },
  { name: "Синагога", imagesrc: "./images/locations/sinagoga.webp" },
  { name: "Скалодром", imagesrc: "./images/locations/climbClub.webp" },
  { name: "Скейт площадка", imagesrc: "./images/locations/skateboarding.webp" },
  { name: "Стадион", imagesrc: "./images/locations/stadium.webp" },
  { name: "Стриптиз клуб", imagesrc: "./images/locations/poleDanceClub.webp" },
  { name: "Стройка", imagesrc: "./images/locations/building.webp" },
  { name: "Супермаркет", imagesrc: "./images/locations/supermarket.webp" },
  { name: "Театр", imagesrc: "./images/locations/theatr.webp" },
  {
    name: "Турнир по настолкам",
    imagesrc: "./images/locations/tableGames.webp",
  },
  { name: "Университет", imagesrc: "./images/locations/university.webp" },
  { name: "Фестиваль пива", imagesrc: "./images/locations/octoberFest.webp" },
  {
    name: "Фестиваль фонарей",
    imagesrc: "./images/locations/lanternFest.webp",
  },
  { name: "Фитнес центр", imagesrc: "./images/locations/fitness.webp" },
  { name: "Химическая лаборатория", imagesrc: "./images/locations/lab.webp" },
  { name: "Чайна-таун", imagesrc: "./images/locations/chinaTown.webp" },
  { name: "Шахта", imagesrc: "./images/locations/mine.webp" },
  { name: "Школа", imagesrc: "./images/locations/school.webp" },
  {
    name: "Шоколадная фабрика",
    imagesrc: "./images/locations/ChocolateFactory.webp",
  },
  { name: "Экскурсионный автобус", imagesrc: "./images/locations/redBus.webp" },
  { name: "Яхт-клуб", imagesrc: "./images/locations/yachtClub.webp" },
];
export const ROLES = {
  spy: "spy",
  innocent: "innocent",
};

export const CLASSNAMES = {
  visible: "shown",
  toDelete: "toDelete",
  invalid: "invalid",
  hidden: "hidden",
  deleting: "deleting",
};
